### ISSUE TITLE
How should we format the three functions(merge, section, difference)?

### ISSUE THREAD

**Issue by mssevov18** [VTStanchev18/Project-Plurality#4]
We need to decide how to _format_ the three functions -> merge, section, difference

**Option 1:**
We let the user choose what sets to use in the function.
We will create a new set with the results

**Option 2:**
We use the first 2 sets.
We will create a new set with the results

I think that option 1 would be much better.
@VTStanchev18 @bbkanev18 @GAMihov18 @ADLaleva

**Comment by GAMihov18** [comment]
**Option 1** would be the better option since it gives much more freedom to the user. Plus if we use **Option 2** we would have made the multiple set system for nothing.

**Comment by mssevov18** [comment]
Agreed.
